<?php
$base = __DIR__;
$profiles = $base . '/profiles';
if (!is_dir($profiles)) mkdir($profiles, 0775, true);
$default = 'Retro 1940s boogie-woogie album cover featuring [THEME], restless rhythmic atmosphere, playful urban energy, bold vintage pulp illustration, large clear typography reading "Boogie Woogie" as the only text, integrated naturally into the artwork, high-contrast halftone texture, no extra text, no logos, no record labels --ar 1:1 --v 6.0';
function json_out($data, int $status=200): void { http_response_code($status); header('Content-Type: application/json'); echo json_encode($data, JSON_UNESCAPED_SLASHES); exit; }
function safe_name(string $name): bool { return $name !== '' && !in_array($name, ['.','..'], true) && !preg_match('/[\\/:*?"<>|]/', $name); }
$path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$method = $_SERVER['REQUEST_METHOD'];
if ($path === '/api/profiles' && $method === 'GET') { json_out(array_map(fn($f)=>pathinfo($f, PATHINFO_FILENAME), glob($profiles.'/*.json'))); }
if (preg_match('#^/api/profiles/(.+)$#', $path, $m)) {
  $name = urldecode($m[1]); $file = $profiles . '/' . $name . '.json';
  if ($method === 'GET') { if (!is_file($file)) json_out(['error'=>'not found'],404); json_out(json_decode(file_get_contents($file), true)); }
  if (!safe_name($name)) json_out(['error'=>'invalid name'],400);
  if ($method === 'PUT') { $data=json_decode(file_get_contents('php://input'),true); if (!is_array($data)) json_out(['error'=>'invalid JSON'],400); file_put_contents($file,json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)); json_out(['ok'=>true]); }
  if ($method === 'DELETE') { if (is_file($file)) unlink($file); json_out(['ok'=>true]); }
}
if ($path !== '/' && $path !== '/index.php') { http_response_code(404); echo 'Not found'; exit; }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Prompt Combiner PHP</title><style>*{box-sizing:border-box}body{margin:0;background:#111827;color:#e5e7eb;font:15px Arial,sans-serif}main{max-width:1100px;margin:auto;padding:24px}h1{margin:0 0 6px}p{color:#9ca3af}.card{background:#1f2937;border:1px solid #374151;border-radius:12px;padding:18px;margin:16px 0}label{display:block;font-weight:bold;margin-bottom:8px}textarea{width:100%;background:#111827;color:#f9fafb;border:1px solid #4b5563;border-radius:8px;padding:12px;font:14px Consolas,monospace;resize:vertical}#master{min-height:120px}.vars{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:14px}.var textarea{min-height:130px}.bar{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.count{margin-right:auto;color:#9ca3af}button,select,input{height:40px;border-radius:7px;padding:0 12px}button{border:0;background:#2563eb;color:white;font-weight:bold;cursor:pointer}select,input{background:#111827;color:#fff;border:1px solid #536174}#result{min-height:280px}.error{color:#fca5a5;margin-top:10px}</style></head><body><main><h1>Prompt Combiner</h1><p>PHP version. Values one per line. Detected [VARIABLES] become combinations.</p><div class="card"><label>Prompt collection</label><div class="bar"><select id="profile"></select><input id="profileName" placeholder="Collection name"><button id="new">New</button><button id="save">Save</button><button id="delete">Delete</button></div></div><div class="card"><label for="master">Master Prompt</label><textarea id="master" spellcheck="false"><?=htmlspecialchars($default, ENT_QUOTES)?></textarea></div><div class="card"><label>Variables</label><div id="variables" class="vars"></div><span id="empty">No variables.</span></div><div class="card"><div class="bar"><span id="count" class="count">0 combinations</span><label>Max prompts <input id="max" type="number" min="1" value="100"></label><label><input id="random" type="checkbox" checked> Randomize</label><button id="generate">Generate</button><button id="copy">Copy</button></div><div id="error" class="error"></div></div><div class="card"><label for="result">Result</label><textarea id="result" readonly></textarea></div></main><script>
const $=s=>document.querySelector(s), master=$('#master'), vars=$('#variables'), count=$('#count'), error=$('#error'), profile=$('#profile');let boxes={};
function names(){return [...new Set([...master.value.matchAll(/\[([A-Za-z_][A-Za-z0-9_]*)\]/g)].map(x=>x[1]))]}
function rebuild(){let old={};for(let [n,b] of Object.entries(boxes))old[n]=b.value;boxes={};vars.innerHTML='';let ns=names();$('#empty').style.display=ns.length?'none':'block';ns.forEach(n=>{let w=document.createElement('div'),l=document.createElement('label'),b=document.createElement('textarea');l.textContent='['+n+']';b.placeholder='One value per line';b.value=old[n]||'';b.oninput=update;w.className='var';w.append(l,b);vars.append(w);boxes[n]=b});update()}
function values(){let o={};for(let [n,b] of Object.entries(boxes))o[n]=b.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);return o}
function update(){let v=values(),t=1;if(Object.values(v).some(x=>!x.length))t=0;else for(let x of Object.values(v))t*=x.length;count.textContent=t.toLocaleString()+' combinations'}
async function api(url,opt){let r=await fetch(url,opt);return [r,await r.json()]}
async function load(n){let [,d]=await api('/api/profiles/'+encodeURIComponent(n));master.value=d.master_prompt||'';$('#max').value=d.max_prompts||100;$('#random').checked=d.randomize!==false;rebuild();for(let [k,v] of Object.entries(d.variables||{}))if(boxes[k])boxes[k].value=v.join('\n');update()}
async function profiles(target=''){let [,a]=await api('/api/profiles');profile.innerHTML=a.map(n=>'<option>'+n+'</option>').join('');if(target||a[0]){profile.value=target||a[0];await load(profile.value)}}
$('#generate').onclick=()=>{error.textContent='';let ns=names(),v=values(),limit=Math.max(1,+$('#max').value||1);if(ns.some(n=>!v[n].length)){error.textContent='Each variable needs one value.';return}let sizes=ns.map(n=>v[n].length),total=sizes.reduce((a,b)=>a*b,1),wanted=Math.min(limit,total),ix=[...Array(total).keys()];if($('#random').checked)ix.sort(()=>Math.random()-.5);let out=ix.slice(0,wanted).map(index=>{let m={};for(let i=ns.length-1;i>=0;i--){m[ns[i]]=v[ns[i]][index%sizes[i]];index=Math.floor(index/sizes[i])}return master.value.replace(/\[([A-Za-z_][A-Za-z0-9_]*)\]/g,(_,n)=>m[n]??_)});$('#result').value=out.join('\n');count.textContent=out.length.toLocaleString()+' prompts generated'};
$('#save').onclick=async()=>{let n=($('#profileName').value||profile.value).trim();if(!n){error.textContent='Enter collection name.';return}await api('/api/profiles/'+encodeURIComponent(n),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({master_prompt:master.value,variables:values(),max_prompts:+$('#max').value||1,randomize:$('#random').checked})});$('#profileName').value='';await profiles(n);error.textContent='Collection saved.'};$(
